version: '3'
services:
  rabbitMQ:
    image: rabbitmq:3-management-alpine
    container_name: rabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '5672:5672'
      - '15672:15672'
  db:
    image: mariadb:11.0
    container_name: maria_db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: microservices
      MARIADB_USER: root
    ports:
      - '3306:3306'
